version: "3"

vars:
  JWT_CLI_IMAGE: bitnami/jwt-cli:6
  ENV_KEYS_PATH: "{{.ROOT_DIR}}/.env.keys"
  KEYCLOAK_HOSTNAME_URL: "{{.KEYCLOAK_HOST}}:{{.KEYCLOAK_PORT}}"
  # Base URL of the Keycloak server including realm path
  # Must be accessible from inside the Docker container running the auth service
  KEYCLOAK_SUPABASE_URL: "{{.KEYCLOAK_HOSTNAME_URL}}/realms/{{.KEYCLOAK_REALM}}"

env:
  KEYCLOAK_HOSTNAME_URL: "{{.KEYCLOAK_HOSTNAME_URL}}"
  KEYCLOAK_SUPABASE_URL: "{{.KEYCLOAK_SUPABASE_URL}}"

dotenv: [.env, .env.default, .env.keys]

includes:
  central: ./central-services/Taskfile.yml

tasks:
  echo-anon-key:
    cmds:
      - >
        docker run --rm {{.JWT_CLI_IMAGE}} encode --alg HS256 --secret {{.SUPABASE_JWT_SECRET}}
        --exp="2y"
        --iss="supabase-demo"
        --payload="role=anon"

  echo-service-key:
    cmds:
      - >
        docker run --rm {{.JWT_CLI_IMAGE}} encode --alg HS256 --secret {{.SUPABASE_JWT_SECRET}}
        --exp="2y"
        --iss="supabase-demo"
        --payload="role=service_role"

  gen-keys:
    desc: Generate new JWT tokens for Supabase anonymous and service role access
    vars:
      SUPABASE_ANON_KEY:
        sh: task echo-anon-key
      SUPABASE_SERVICE_ROLE_KEY:
        sh: task echo-service-key
    cmds:
      - echo "SUPABASE_ANON_KEY={{.SUPABASE_ANON_KEY}}" > {{.ENV_KEYS_PATH}}
      - echo "SUPABASE_SERVICE_ROLE_KEY={{.SUPABASE_SERVICE_ROLE_KEY}}" >> {{.ENV_KEYS_PATH}}
    status:
      - test -f {{.ENV_KEYS_PATH}}

  dev-webui:
    desc: Start the open access tool web application in development mode
    dir: "{{.ROOT_DIR}}/open-access-tool"
    env:
      VITE_SUPABASE_ANON_KEY: "{{.SUPABASE_ANON_KEY}}"
      VITE_KEYCLOAK_CLIENT_ID: "{{.KEYCLOAK_SUPABASE_CLIENT_ID}}"
      VITE_KEYCLOAK_URL: "{{.KEYCLOAK_HOSTNAME_URL}}"
      VITE_KEYCLOAK_REALM: "{{.KEYCLOAK_REALM}}"
      VITE_SERVICE_API_HOST: "{{.RELIFE_SERVICE_API_HOST}}"
      VITE_SERVICE_API_PORT: "{{.RELIFE_SERVICE_API_PORT}}"
    cmds:
      - npm install
      - npm run dev

  dev-service-api:
    desc: Start the service API in development mode
    dir: "{{.ROOT_DIR}}/service-api"
    env:
      SUPABASE_URL: "{{.SUPABASE_URL}}"
      SUPABASE_KEY: "{{.SUPABASE_SERVICE_ROLE_KEY}}"
      KEYCLOAK_CLIENT_ID: "{{.KEYCLOAK_RELIFE_SERVICE_CLIENT_ID}}"
      KEYCLOAK_CLIENT_SECRET: "{{.KEYCLOAK_RELIFE_SERVICE_CLIENT_SECRET}}"
    cmds:
      - uv sync
      - >
        uv run fastapi dev --reload
        --host {{.RELIFE_SERVICE_API_HOST}}
        --port {{.RELIFE_SERVICE_API_PORT}}
        src/service_api/app.py

  clean:
    desc: Stop and remove all running services and clean up associated data
    cmds:
      - task: central:clean
      - cmd: rm -f {{.ENV_KEYS_PATH}}
        ignore_error: true
