name: relife-keycloak
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    restart: on-failure
    ports:
      - ${KEYCLOAK_PORT}:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - start-dev
    environment:
      # Keycloak admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Postgres database credentials
      KC_DB: postgres
      KC_DB_USERNAME: ${SUPABASE_POSTGRES_USER}
      KC_DB_PASSWORD: ${SUPABASE_POSTGRES_PASSWORD}
      KC_DB_URL_PORT: ${SUPABASE_POSTGRES_PORT}
      KC_DB_URL_DATABASE: ${KEYCLOAK_POSTGRES_DBNAME}
      KC_DB_URL_HOST: host.docker.internal
      # Logging configuration
      KC_LOG_CONSOLE_COLOR: "true"
      KC_LOG_LEVEL: debug
      # Keycloak proxy configuration
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_DEBUG: true
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME_URL}
      KC_HOSTNAME_ADMIN: ${KEYCLOAK_HOSTNAME_URL}
      KC_HTTP_ENABLED: true
