version: "3"

includes:
  backup: ./Taskfile.backup.yml
  proxy: ./Taskfile.proxy.yml

vars:
  SUPABASE_GIT_URL: https://github.com/supabase/supabase
  SUPABASE_GIT_TREEISH: v1.24.09
  SUPABASE_GIT_DIR: "{{.TASKFILE_DIR}}/src-supabase"
  MAIN_IP_ADDRESS:
    sh: ip route get 1.2.3.4 | awk '{print $7}' | tr -d '\n' | xargs
  POSTGRES_IMAGE: postgres:16
  POSTGRES_CONNECTION_STRING: "postgres://{{.SUPABASE_POSTGRES_USER}}:{{.SUPABASE_POSTGRES_PASSWORD}}@{{.MAIN_IP_ADDRESS}}:{{.SUPABASE_POSTGRES_PORT}}"
  POSTGRES_CONNECTION_STRING_WITH_DB: "{{.POSTGRES_CONNECTION_STRING}}/{{.SUPABASE_POSTGRES_DBNAME}}"
  KC_HOSTNAME_STRICT:
    sh: 'if echo "{{.KEYCLOAK_HOSTNAME_URL}}" | grep -q "^https://"; then echo "true"; else echo "false"; fi'

env:
  KC_HOSTNAME_STRICT: "{{.KC_HOSTNAME_STRICT}}"

tasks:
  supabase-clone:
    # https://supabase.com/docs/guides/self-hosting/docker#installing-and-running-supabase
    desc: Clone the Supabase repository with minimal history and sparse checkout for docker files only
    cmds:
      - git clone --filter=blob:none --no-checkout {{.SUPABASE_GIT_URL}} {{.SUPABASE_GIT_DIR}}
      - >
        cd {{.SUPABASE_GIT_DIR}} &&
        git sparse-checkout set --cone docker &&
        git checkout {{.SUPABASE_GIT_TREEISH}}
    status:
      - test -d {{.SUPABASE_GIT_DIR}}

  supabase-init:
    deps:
      - supabase-clone
    cmds:
      - envsubst < {{.TASKFILE_DIR}}/.env.supabase.tmpl > {{.SUPABASE_GIT_DIR}}/docker/.env
      - cp -f {{.TASKFILE_DIR}}/docker-compose-supabase.yml {{.SUPABASE_GIT_DIR}}/docker/docker-compose.yml
    preconditions:
      - test -f {{.ENV_KEYS_PATH}}

  supabase-migrate:
    desc: Run the migrations for the Supabase project
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - supabase migrations up --db-url {{.POSTGRES_CONNECTION_STRING_WITH_DB}}

  supabase-restore:
    desc: Restore a SQL dump file to the Supabase database
    sources:
      - "{{.TASKFILE_DIR}}/supabase/seeds/*.sql"
    method: none
    cmds:
      - for: sources
        cmd: >
          docker run --rm -i
          -v {{.ROOT_DIR}}/{{.ITEM}}:/dump.sql
          {{.POSTGRES_IMAGE}}
          psql {{.POSTGRES_CONNECTION_STRING_WITH_DB}} -f /dump.sql

  supabase-deploy:
    desc: Deploy all Supabase services using Docker Compose in detached mode
    deps:
      - supabase-init
    dir: "{{.SUPABASE_GIT_DIR}}/docker"
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.s3.yml up -d

  supabase-clean:
    desc: Stop and remove all Supabase services and their volumes, then clean up the cloned repository
    cmds:
      - cmd: cd {{.SUPABASE_GIT_DIR}}/docker && docker compose -f docker-compose.yml -f docker-compose.s3.yml down -v
        ignore_error: true
      - cmd: rm -fr {{.SUPABASE_GIT_DIR}}
        ignore_error: true

  supabase-pgurl:
    desc: Print the PostgreSQL connection string for the Supabase project
    silent: true
    cmds:
      - echo "{{.POSTGRES_CONNECTION_STRING_WITH_DB}}"

  create-keycloak-db:
    cmds:
      - >
        docker run --rm -it {{.POSTGRES_IMAGE}}
        psql {{.POSTGRES_CONNECTION_STRING}}/postgres
        --command="CREATE DATABASE {{.KEYCLOAK_POSTGRES_DBNAME}};"
    status:
      - >
        docker run --rm {{.POSTGRES_IMAGE}}
        psql {{.POSTGRES_CONNECTION_STRING}}/postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{.KEYCLOAK_POSTGRES_DBNAME}}'" | grep 1

  keycloak-deploy:
    desc: Deploy Keycloak service using Docker Compose
    deps:
      - create-keycloak-db
    cmds:
      - docker compose -f {{.TASKFILE_DIR}}/docker-compose-keycloak.yml up -d --build --wait

  keycloak-clean:
    desc: Stop and remove the Keycloak service and its associated volumes
    cmds:
      - docker compose -f {{.TASKFILE_DIR}}/docker-compose-keycloak.yml down -v

  deploy:
    desc: Deploy all central services
    vars:
      SLEEP_SECONDS: 10
    cmds:
      - task: supabase-deploy
      - sleep {{.SLEEP_SECONDS}}
      - task: supabase-migrate
      - task: supabase-restore
      - task: keycloak-deploy

  clean:
    desc: Stop and remove all central services (Supabase and Keycloak) and their associated data
    cmds:
      - task: supabase-clean
      - task: keycloak-clean

  force-remove-source:
    desc: Force remove the Supabase source directory by mounting it to a container as a workaround for lacking root access on the host
    cmds:
      - docker run --rm -it -v {{.ROOT_DIR}}/central-services:/code alpine rm -fr /code/src-supabase
