version: "3"

vars:
  SUPABASE_COMPOSE_PROJECT_NAME: supabase
  SUPABASE_GIT_URL: https://github.com/supabase/supabase
  SUPABASE_GIT_TREEISH: v1.24.09
  SUPABASE_GIT_DIR: "{{.TASKFILE_DIR}}/supabase"
  POSTGRES_IMAGE: postgres:16
  POSTGRES_CONNECTION_STRING: "postgres://{{.SUPABASE_POSTGRES_USER}}:{{.SUPABASE_POSTGRES_PASSWORD}}@host.docker.internal:{{.SUPABASE_POSTGRES_PORT}}"
  KEYCLOAK_COMPOSE_PROJECT_NAME: keycloak

tasks:
  supabase-clone:
    # https://supabase.com/docs/guides/self-hosting/docker#installing-and-running-supabase
    desc: Clone the Supabase repository
    cmds:
      - git clone --filter=blob:none --no-checkout {{.SUPABASE_GIT_URL}} {{.SUPABASE_GIT_DIR}}
      - >
        cd {{.SUPABASE_GIT_DIR}} &&
        git sparse-checkout set --cone docker &&
        git checkout {{.SUPABASE_GIT_TREEISH}}
    status:
      - test -d {{.SUPABASE_GIT_DIR}}

  supabase-init:
    deps:
      - supabase-clone
    dir: "{{.SUPABASE_GIT_DIR}}/docker"
    cmds:
      - cp .env.example .env
      - docker compose -p {{.SUPABASE_COMPOSE_PROJECT_NAME}} pull
    status:
      - test -f {{.SUPABASE_GIT_DIR}}/docker/.env

  supabase-deploy:
    desc: Deploy the Supabase services
    deps:
      - supabase-init
    dir: "{{.SUPABASE_GIT_DIR}}/docker"
    cmds:
      - docker compose -p {{.SUPABASE_COMPOSE_PROJECT_NAME}} up -d --build

  supabase-clean:
    desc: Stop and remove the Supabase services
    cmds:
      - docker compose -p {{.SUPABASE_COMPOSE_PROJECT_NAME}} down -v
      - cmd: rm {{.SUPABASE_GIT_DIR}}/docker/.env
        ignore_error: true

  create-keycloak-db:
    desc: Create a new database for Keycloak in the PostgreSQL database
    cmds:
      - >
        docker run --rm -it {{.POSTGRES_IMAGE}}
        psql {{.POSTGRES_CONNECTION_STRING}}/postgres
        --command="CREATE DATABASE {{.KEYCLOAK_POSTGRES_DBNAME}};"
    status:
      - >
        docker run --rm {{.POSTGRES_IMAGE}}
        psql {{.POSTGRES_CONNECTION_STRING}}/postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{.KEYCLOAK_POSTGRES_DBNAME}}'" | grep 1

  keycloak-deploy:
    desc: Deploy the Keycloak services
    deps:
      - create-keycloak-db
    cmds:
      - docker compose -p {{.KEYCLOAK_COMPOSE_PROJECT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose-keycloak.yml up -d --build --wait
